#!/bin/bash

##############
# Testing!!! #
##############
echo "##############"
echo "# Testing!!! #"
echo "##############"
CUR_DIR="./"
SCRIPT_DIR="$CUR_DIR/scripts"
#
# Start with cleanup the all logging executing processes
$SCRIPT_DIR/cleanup.sh

DATADIR="/data"
DATAFOLDER="size10"
DATASET=$DATADIR/$DATAFOLDER

MODEL="resnet18"
SCRIPT="test_py_wrapper.sh"

BATCH=512
WORKERS=4
THREADS=1
##########
# Single #
##########

TYPE="SINGLE"; EPOCH=10
# TYPE="SINGLE"; EPOCH=255
DATAFOLDER="1024batch"
DATASET=$DATADIR/$DATAFOLDER
# Threads for mini batch size
$SCRIPT_DIR/$SCRIPT $TYPE fordebug $DATASET $MODEL $EPOCH $BATCH $WORKERS 2 norandom
$SCRIPT_DIR/$SCRIPT $TYPE fordebug $DATASET $MODEL $EPOCH $BATCH $WORKERS 4 norandom
$SCRIPT_DIR/$SCRIPT $TYPE fordebug $DATASET $MODEL $EPOCH $BATCH $WORKERS 8 norandom
$SCRIPT_DIR/$SCRIPT $TYPE fordebug $DATASET $MODEL $EPOCH $BATCH $WORKERS 16 norandom
$SCRIPT_DIR/$SCRIPT $TYPE fordebug $DATASET $MODEL $EPOCH $BATCH $WORKERS 32 norandom
$SCRIPT_DIR/$SCRIPT $TYPE fordebug $DATASET $MODEL $EPOCH $BATCH $WORKERS 64 norandom
$SCRIPT_DIR/$SCRIPT $TYPE fordebug $DATASET $MODEL $EPOCH $BATCH $WORKERS 128 norandom
$SCRIPT_DIR/$SCRIPT $TYPE fordebugnative $DATASET $MODEL $EPOCH $BATCH $WORKERS 0 norandom
# $SCRIPT_DIR/$SCRIPT $TYPE trainNoAMP $DATASET $MODEL $EPOCH $BATCH 2 $THREADS norandom $OPTION $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE loadNtrainPWPMPinNoAMP $DATASET $MODEL $EPOCH $BATCH 2 $THREADS norandom $OPTION $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinShared $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION $OPTION
# EPOCH=3
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATADIR/size512 $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION $OPTION

#######
# DDP #
#######
TYPE="DDP"; EPOCH=5
BATCH=$(($BATCH*4))
WORKERS=$(($WORKERS*4))


# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSampler $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION $OPTION

# $SCRIPT_DIR/$SCRIPT $TYPE train $DATASET $MODEL $EPOCH $BATCH 4 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE trainNoAMP $DATASET $MODEL $EPOCH $BATCH 2 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE loadNtrainPWPMPin $DATASET $MODEL $EPOCH $BATCH 4 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE loadNtrainPWPMPinNoAMP $DATASET $MODEL $EPOCH $BATCH 2 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSampler $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION
# EPOCH=3
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATADIR/size320 $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION

WORKERS=4
BATCH=512
TYPE="DDP2GPU"; EPOCH=1
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATADIR/size320 $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION


# TYPE="DDP2GPUTwoSocket"; EPOCH=5
# DATAFOLDER="size10"
# DATASET=$DATADIR/$DATAFOLDER
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSamplerTwoGPU $DATASET $MODEL $EPOCH 512 8 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATADIR/size320 $MODEL $EPOCH 512 8 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrainTwoGPU $DATADIR/size320 $MODEL $EPOCH 512 8 $THREADS norandom $OPTION


TYPE="DDP2GPUNoDiskSocket"; EPOCH=5
DATAFOLDER="size10"
DATASET=$DATADIR/$DATAFOLDER
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSamplerTwoGPUdiffsocket $DATASET $MODEL $EPOCH 512 8 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrainTwoGPUdiffSocket $DATADIR/size320 $MODEL $EPOCH 512 8 $THREADS norandom $OPTION


TYPE="DDPMANUAL"; EPOCH=5
DATAFOLDER="size10"
DATASET=$DATADIR/$DATAFOLDER
# $SCRIPT_DIR/$SCRIPT $TYPE train $DATASET $MODEL $EPOCH $BATCH 4 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE loadNtrainPWPMPin $DATASET $MODEL $EPOCH $BATCH 4 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSampler $DATASET $MODEL $EPOCH $BATCH 4 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATADIR/size320 $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION
#sleep 1m
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSamplerNoAMP $DATASET $MODEL $EPOCH $BATCH 4 $THREADS norandom $OPTION
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrainNoAMP $DATADIR/size320 $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom $OPTION

echo "##############"
echo "# Testing!!! #"
echo "##############"