#!/bin/bash

SHELL=`basename "$0"`

if [ $# != 0 ]; then
    echo "$SHELL: USAGE: $SHELL"
    # echo "$SHELL: e.g. (upload bandwidth(Kbps): 10000, 20000, ..."
    # echo "$SHELL: e.g. (the number of target edge group):  1, 2, 3, ..."
    exit 1
fi

CUR_DIR="./"
SCRIPT_DIR="$CUR_DIR/scripts"
# DATASET DIR
DATADIR="/data"

# Start with cleanup the all logging executing processes
$SCRIPT_DIR/cleanup.sh

MODEL="resnet18"
SCRIPT="test_py_wrapper.sh"

BATCH=512
WORKERS=4
THREADS=0

# WORKERS=8

##########
# Single #
##########
TYPE="SINGLEFULLTRACE"; EPOCH=1
MODEL="resnet50"
DATAFOLDER="size2"
DATASET=$DATADIR/$DATAFOLDER
WORKERS=1; BATCH=512
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS default TRACEFETCH
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom TRACEFETCH
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugmentnorandom TRACEFETCH
# WORKERS=3
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS default TRACEFETCH
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom TRACEFETCH
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugmentnorandom TRACEFETCH

############
# DDP 4GPU #
############
WORKERS=5; BATCH=512;
TYPE="DDP4GPUFULLTRACE"; EPOCH=1
NUM_GPU=4
BATCH=$(($BATCH*$NUM_GPU))
WORKERS=$(($WORKERS*$NUM_GPU))
MODEL="resnet50"
DATAFOLDER="size2"
DATASET=$DATADIR/$DATAFOLDER
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom TRACEFETCH
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugmentnorandom TRACEFETCH TRACEAUG

DATAFOLDER="Imagenet"
DATASET=$DATADIR/$DATAFOLDER; EPOCH=1
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS default TRACEFETCH TRACEAUG
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugment TRACEFETCH TRACEAUG

# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugmentnorandom TRACEFETCH TRACEAUG
# EPOCH=1
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugmentnorandom TRACEAUG
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrainNoPinCPU $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS default
WORKERS=5; EPOCH=1
WORKERS=$(($WORKERS*$NUM_GPU))
DATAFOLDER="imagenet-pytorch"
DATASET=$DATADIR/$DATAFOLDER
$SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS default FETCHTRACE
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrainMicro $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugment
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrainRefurbish $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugment
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugment
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrainIO $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugment
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS randaugment
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS default


#######
# DDP #
#######
# TYPE="DDPFULLTRACESEED"; EPOCH=5
# TYPE="DDPFULLTRACE"; EPOCH=1
TYPE="DDP"; EPOCH=5
BATCH=$(($BATCH*4))
WORKERS=$(($WORKERS*4))
THREADS=0

DATAFOLDER="size80iter"
DATASET=$DATADIR/$DATAFOLDER
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSampler $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom

DATAFOLDER="size10"
DATASET=$DATADIR/$DATAFOLDER
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE train $DATASET $MODEL $EPOCH $BATCH 4 $THREADS norandom
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE trainNoAMP $DATASET $MODEL $EPOCH $BATCH 2 $THREADS norandom
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE loadNtrainPWPMPin $DATASET $MODEL $EPOCH $BATCH 4 $THREADS norandom
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE loadNtrainPWPMPinNoAMP $DATASET $MODEL $EPOCH $BATCH 2 $THREADS norandom
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSampler $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom
# EPOCH=3
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATADIR/size320 $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom


TYPE="DDP2GPU"; EPOCH=5
DATAFOLDER="size10"
DATASET=$DATADIR/$DATAFOLDER
# sleep 15m
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSampler $DATASET $MODEL $EPOCH 512 8 $THREADS norandom
# sleep 15m
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATADIR/size320 $MODEL $EPOCH 512 8 $THREADS norandom


# TYPE="DDP2GPUTwoSocket"; EPOCH=5
# DATAFOLDER="size10"
# DATASET=$DATADIR/$DATAFOLDER
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSamplerTwoGPU $DATASET $MODEL $EPOCH 512 8 $THREADS norandom
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrainTwoGPU $DATADIR/size320 $MODEL $EPOCH 512 8 $THREADS norandom


TYPE="DDP2GPUNoDiskSocket"; EPOCH=5
DATAFOLDER="size10"
DATASET=$DATADIR/$DATAFOLDER
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSamplerTwoGPUdiffsocket $DATASET $MODEL $EPOCH 512 8 $THREADS norandom
# sleep 5m
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrainTwoGPUdiffSocket $DATADIR/size320 $MODEL $EPOCH 512 8 $THREADS norandom


TYPE="DDPFULLTRACE"; EPOCH=1 
DATAFOLDER="size10"
DATASET=$DATADIR/$DATAFOLDER
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSampler $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom
# sleep 3m
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom
# sleep 3m
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom

TYPE="DDPFULLTRACE2GPU"; EPOCH=1
DATAFOLDER="size10"
DATASET=$DATADIR/$DATAFOLDER
# $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSampler $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom
# sleep 3m
# $SCRIPT_DIR/$SCRIPT $TYPE fsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom
# sleep 3m
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATASET $MODEL $EPOCH $BATCH $WORKERS $THREADS norandom


# TYPE="DDPMANUALFULLTRACE"; EPOCH=1
# DATAFOLDER="size320"
# DATASET=$DATADIR/$DATAFOLDER
# # sleep 5m
# # $SCRIPT_DIR/$SCRIPT $TYPE prepNloadNtrainPMPWPinOverwriteSampler $DATASET $MODEL $EPOCH 256 4 $THREADS norandom
# $SCRIPT_DIR/$SCRIPT $TYPE fetchNfsNprepNloadNtrain $DATASET $MODEL $EPOCH 256 4 $THREADS norandom
# # sleep 5m

