#!/bin/bash

pkill -ef -9 "free -h"
pkill -ef -9 "iostat -p"
pkill -ef -9 "cpustat"
sudo pkill -ef -9 "cachestat"
sudo pkill -ef -9 "pcm -csv"
sudo pkill -ef -9 "pcm-memory"
sudo pkill -ef -9 "pcm-core"
sudo pkill -ef -9 "perf stat"
pkill -ef -9 "pyfiles"
pkill -ef -9 "python -O"
pkill -ef -9 "python -OO"
pkill -ef -9 "from"
pkill -ef -9 "ray"
pkill -ef -9 "kite"
pkill -ef -9 "tabnine"
pkill -ef -9 "nvidia-smi_logger"
pkill -9 -ef "logger"
pkill -ef -9 "cpu_temp_logger"